rmarkdown::render('00_preparar_datos.rmd')
rmarkdown::render('01_numero_de_clases.rmd')
rmarkdown::render('02_resultados.rmd')
rmarkdown::render('03_extraer_resultados.rmd')
rmarkdown::render('04_graficos.rmd')
rmarkdown::render('05_ejercicio.rmd')
rmarkdown::render('06_ejercicio_resuelto.rmd')